### ISSUE TITLE
Configuration not saving

### ISSUE THREAD

**Issue by StellarJay77** [karashiiro/TextToTalk#1]
Every time I log out and back in, I have to go into TextToTalk and reselect the channels I want. Uninstalling the plugin and reinstalling gives the same behavior and everything gets set to defaults.

**Comment by karashiiro** [comment]
Aware of the issue, just haven't had time to fix it yet what with maintaining software for Bozja.

**Comment by StellarJay77** [comment]
Thanks. It's only a minor inconvenience. Great plugin though. I'm ADHD and
miss messages all the time as I'm focused on fights and other things and it
is a big help to keep me notified.

**Comment by karashiiro** [comment]
Closed with https://github.com/goatcorp/DalamudPlugins/commit/df6c9551520782091099e0e3e3a7f21b49b3afda
