### ISSUE TITLE
XIV on Mac, Failing to install TextToTalk plugin. 

### ISSUE THREAD

**Issue by 0xChief** [karashiiro/TextToTalk#122]
So the XIV on Mac launcher has support for Dalamud which is how I'm attempting to install TextToTalk

On Mac, I get the failed to install plugin error. Please restart your game and try again error. I can install other plugins but TTS won't ever work.

Has anyone had any success with getting TTS on Mac for FF14?

I made an earlier bug report before but I can confirm that it still fails to install. 

Thanks!

**Comment by karashiiro** [comment]
Sorry, I wasn't aware installation was still broken on Mac. I just released v1.16.2 which should fix the problem. Please let me know if it works or not 🥴

**Comment by 0xChief** [comment]
Was able to instal now, thanks so much!
