### ISSUE TITLE
Cant select TTS Voice

### ISSUE THREAD

**Issue by Kumicoo** [karashiiro/TextToTalk#123]
The option to even select different voices is not there (below volume). Why? My Windows is completely set to english so i can use this and it still reads with the german TTS. Where is that setting? i remember it being there like 2 weeks ago..
![image](https://user-images.githubusercontent.com/35538818/188520566-397935fa-2a0f-45d7-86ac-70670e6935de.png)

**Comment by karashiiro** [comment]
Sorry, I didn't notice that when I was testing things for the most recent update. This should be fixed once https://github.com/goatcorp/DalamudPluginsD17/pull/413 is merged.
