### ISSUE TITLE
Enabling "Use gendered voices" bugs out the settings panel.

### ISSUE THREAD

**Issue by ryankhart** [karashiiro/TextToTalk#126]
Can anyone else reproduce this bug? I just returned to the game after a long break and after accidentally deleting my plugin settings in a Windows reinstall.

See GIF below. Notice how, when the setting is enabled, everything after it and the tabs to the right of the current tab disappear.

![Animation](https://user-images.githubusercontent.com/3673962/198208132-0a193a21-a9aa-44cb-9807-3ca66537e879.gif)

**Comment by ryankhart** [comment]
I just tried backing up my settings (TextToTalk.json and TextToTalk\VoicePresets.json) and disabled and re-enabled the plugin, check to make sure that all the settings were default, and now it shows like this in this GIF below.

![Animation](https://user-images.githubusercontent.com/3673962/198211366-3a081f6f-004b-43b2-99b6-a875367bceb2.gif)

**Comment by ryankhart** [comment]
I've restored by backup again, and I also tried creating a new access key and put those credentials in there, and it still behaves like in the first GIF.

**Comment by siwatpru** [comment]
+1 I'm having the same problem for "Use gendered voices" option.

**Comment by karashiiro** [comment]
Does this happen on the normal version or the testing version of the plugin, or both?

**Comment by ryankhart** [comment]
I can't believe I didn't think to test that.

I've reverted back to the normal release version of TextToTalk on 1.16.3.0, and it works as expected, so something happened after that release.

**Comment by karashiiro** [comment]
Should be fixed in testing v1.17.1
