### ISSUE TITLE
Impliment Azure Cognitive Services

### ISSUE THREAD

**Issue by Spankachu** [karashiiro/TextToTalk#129]
Please implement Azure's Test-to-speach, which in many cases sounds better than Polly, and has many more choices in voices.

https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?pivots=programming-language-csharp&tabs=windows%2Cterminal

**Comment by karashiiro** [comment]
Implemented in testing v1.18 - this should make it to a stable release by the end of the week.
