### ISSUE TITLE
TTT Plugin not longer working / Installation error

### ISSUE THREAD

**Issue by Waitsnake** [karashiiro/TextToTalk#135]
TTT plugin stopped completely working for me with new 1.18.2.0 today.
Tried to uninstall and install it again after a windows reboot, but during install it gives now this installation error?
![tt_err](https://user-images.githubusercontent.com/942085/209698202-fc9e565a-7b54-45a4-81da-05024554f0ef.PNG)

**Comment by Waitsnake** [comment]
Ok, got it back running by renaming my old config under:
C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\TextToTalk\VoicePresets.json

A diff shows new entries witch makes old and new config format aparently incompatible.
![image](https://user-images.githubusercontent.com/942085/209699816-f0cf9d5a-17ba-4ad6-b697-2879bb29b9e0.png)
(see new entries on right side of diff )

In case a plugin update changes to an incompatible new config format it would be nice if it will be handled by plugin with a message, that old config needs to be delated (and then delated) or updated to new format. Otherwise some user maybe a bit clueless and don't know what to do.

Remembers me I had also struggles with some previous updates with config. It was still working but all system voices I had configured where all of the sudden set to volume 0. This took me a while too to find the cause.

**Comment by karashiiro** [comment]
> In case a plugin update changes to an incompatible new config format it would be nice if it will be handled by plugin with a message, that old config needs to be delated (and then delated) or updated to new format. Otherwise some user maybe a bit clueless and don't know what to do.

It's always supposed to be handled automatically. This update has just had a lot of conflicting changes to adjust for, so none of this was caught in testing.

Working on a fix now.

**Comment by Waitsnake** [comment]
Thanks for your hard work Karashiiro.
I just want to help a little with error reports when I struggle myself.
This plugin is actually my most used and loved of all.

**Comment by karashiiro** [comment]
Should be fixed now on v1.18.3

**Comment by Coolykoen** [comment]
Can confirm it skipped .2 and updated to .3 now without issues (i had the same issue as OP.
It works as expected again, thank you for the quick fix :)

**Comment by Reckzx** [comment]
TTT is not working for me I have tried to update it but nothing is working any help for this awesome mob please 


![Uploading TTT ffxiv.png…]()

**Comment by karashiiro** [comment]
That image seems broken.

**Comment by karashiiro** [comment]
Can anyone who is still having this issue send their config files?
Config 1: `%AppData%\XIVLauncher\pluginConfigs\TextToTalk\VoicePresets.json`
Config 2: `%AppData%\XIVLauncher\pluginConfigs\TextToTalk.json`

**Comment by Eorzean** [comment]
The installation error is gone, but it is still not functional.
Issue #134
[VoicePresets.json.txt](https://github.com/karashiiro/TextToTalk/files/10317346/VoicePresets.json.txt)
[TextToTalk.json.txt](https://github.com/karashiiro/TextToTalk/files/10317348/TextToTalk.json.txt)

**Comment by karashiiro** [comment]
> The installation error is gone, but it is still not functional. Issue #134 [VoicePresets.json.txt](https://github.com/karashiiro/TextToTalk/files/10317346/VoicePresets.json.txt) [TextToTalk.json.txt](https://github.com/karashiiro/TextToTalk/files/10317348/TextToTalk.json.txt)

That voice presets config doesn't have any created voice presets, try creating new ones and testing it again

**Comment by Eorzean** [comment]
I just created a new preset and it worked.

**Comment by Waitsnake** [comment]
> Can anyone who is still having this issue send their config files? 

I did not have saved my old TextToTalk.json, but still have my old VoicePresets.json that seams to causes the trouble for me with  1.18.2.0
[_VoicePresets.json.txt](https://github.com/karashiiro/TextToTalk/files/10320134/_VoicePresets.json.txt)

**Comment by karashiiro** [comment]
More fixes up with 1.18.4
