### ISSUE TITLE
Amazon Polly Voices Rate Not Working

### ISSUE THREAD

**Issue by Ahegaoa** [karashiiro/TextToTalk#16]
Amazon Polly Voices work, but changing the rate in the slider doesn't affect the voice speed for them. Is it possible to have rate supported for third party 64-bit voices?

**Comment by karashiiro** [comment]
It is not, it’s up to the provider of any voice libraries to fully support the Windows API features.

Unless rate changing works in ACT, in which case I can look into this.

**Comment by Ahegaoa** [comment]
Using a 6 year old version of the Amazon Polly Voices (Ivona 2) works and changing the rate works too.
