### ISSUE TITLE
Azure Skipping voice lines

### ISSUE THREAD

**Issue by necrovamp** [karashiiro/TextToTalk#160]
I have tested azure, system, and polly. Polly and system work correctly so far. 

I used Azure for about 3 weeks, but in the past week it has been skipping the first lines from any character, and always playing the second, then hit or miss on the rest. I'm on the free tier, with $200 of remain cred. 
The only thing I haven't tried is to change my region. I dont know if this is a bug with TTT, or azure/account, but I just thought I'd mention it.

**Comment by karashiiro** [comment]
Haven't looked into this yet, but last time this was reported, it was due to rate limiting when too many spoken messages happen at once. Azure has a stricter rate limit than the other cloud providers.

**Comment by necrovamp** [comment]
> Haven't looked into this yet, but last time this was reported, it was due to rate limiting when too many spoken messages happen at once. Azure has a stricter rate limit than the other cloud providers.

Understood, I remember reading something about that, I could understand it being the reason for the inconsistent responses in a conversation, but I just thought it was strange, the first response from any character is ignored, then the 2nd chat bubble from the same character is always spoken, no matter if I click through quickly or wait 10 minutes. Wasn't sure if there was anything else possibly  going on

**Comment by necrovamp** [comment]
I did some further testing today and It was not as consistent as I mentioned previously. I'll go ahead and close this issue, as im nto sure there is anything we can do about the rate limiting
