### ISSUE TITLE
Weird pronunciation of words like "thought"

### ISSUE THREAD

**Issue by asuran14** [karashiiro/TextToTalk#161]
It seems that any words that contain "ough" are always pronounced in the way that combination of letters would be in the word "though".  Not the biggest deal I was just wondering if there is some way to prevent this?

**Comment by karashiiro** [comment]
If you're using a voice backend that supports lexicons (it'll have an option in the settings if so), you can create a lexicon to override pronunciations. It's not very intuitive, but there are some examples in the lexicons folder in this repository.

**Comment by asuran14** [comment]
> If you're using a voice backend that supports lexicons (it'll have an option in the settings if so), you can create a lexicon to override pronunciations. It's not very intuitive, but there are some examples in the lexicons folder in this repository.

Thank you, I figured out the issue.  It was the characters locations polly lexicon giving me issues.  I guess it has a deal in there meant for party chat shorthand's to pronounce "tho" as "though".  This ended up hijacking my npc dialog and pronouncing thought and other similar words incorrectly.  I am using polly but just ended up turning it off and using the standard characters locations lexicon and it seems to work just fine now.
