### ISSUE TITLE
1.26.0.0 will not install

### ISSUE THREAD

**Issue by Roctose** [karashiiro/TextToTalk#164]
Attempting to install the testing version of TextToTalk runs up against an error message stating the plugin has failed to install correctly.

Restarting XIV results in the plugin being considered installed in the plugin installer menu, but broken/unusable. Forcing an uninstall and reinstall. 

Checking the installed plugins folder shows that the texttotalk folder is there, but for whatever reason the plugin simply will not load.

**Comment by karashiiro** [comment]
Is there anything in `dalamud.log` about this?

**Comment by Roctose** [comment]
Yes, here you go! This is the whole bit pertaining to Text to Talk
[TTS log.txt](https://github.com/karashiiro/TextToTalk/files/11608431/TTS.log.txt)

**Comment by karashiiro** [comment]
Just released [1.26.1](https://github.com/goatcorp/DalamudPluginsD17/pull/1950), let me know if this fixes the issue.

**Comment by Roctose** [comment]
Gave it another shot, but sadly same result. Here's the log again!
[TTS log 2.txt](https://github.com/karashiiro/TextToTalk/files/11621419/TTS.log.2.txt)

**Comment by karashiiro** [comment]
Released another version, this should fix it

**Comment by Roctose** [comment]
Excellent! That did finally do it. 

I did get in and have an issue where I couldn't select a voice to use via ElevenLabs, but that's a different issue entirely and possibly not something enabled yet. Thanks for all your help!
