### ISSUE TITLE
Cannot input Access or Secret keys for Amazon Polly

### ISSUE THREAD

**Issue by lozmuir** [karashiiro/TextToTalk#172]
Both Access and Secret keys go blank  as soon as they are entered.

**Comment by Filman007** [comment]
Hi, did you solve this?

**Comment by lozmuir** [comment]
Yeah, use the testing version. Go to dalamud experimental settings and tick
"Get plugin testing builds" then right click the TextToTalk plugin in your
installed plugins and tick "Receive plugin testing versions" then reinstall
the plugin and it'll be the testing version (v1.26.3.0).

**Comment by lozmuir** [comment]
I needed to use the testing version to fix this. For anyone else having issues - Go to dalamud experimental settings and tick "Get plugin testing builds" then right click the TextToTalk plugin in your installed plugins and tick "Receive plugin testing versions" then reinstall the plugin and it'll be the testing version (v1.26.3.0).
