### ISSUE TITLE
enabling TTS sometimes reads an old dialogue box that isn't open anymore.

### ISSUE THREAD

**Issue by johnysandels** [karashiiro/TextToTalk#18]

**Comment by karashiiro** [comment]
Will be live with https://github.com/goatcorp/DalamudPlugins/pull/911

**Comment by johnysandels** [comment]
Sorry but it doesn't seem to be fixing the issue I'm having. When re-enabling the tts after a text box is closed, it still reads out what was on the text box. Its most prevalent after re-enabling TTS after finishing a voiced cutscene, since it reads out the last textbox that was open after the cutscene is finished. Here's an example https://streamable.com/g7jb3j

**Comment by karashiiro** [comment]
Closed with https://github.com/karashiiro/TextToTalk/commit/781a6fae27e39d2d15cf6c0697221ffd2362b6f1 - releasing with v1.7.5.
