### ISSUE TITLE
Azure doesn't remember the lexicon settings & error loading it

### ISSUE THREAD

**Issue by SKLCLU** [karashiiro/TextToTalk#180]
Every time I load a lexicon I get an error saying "[Collection was of a fixed size.](https://i.imgur.com/MJbgFpV.png)", and then have to go through the Open lexicon process again to load it. 

The other problem is that it only sticks for that game session. Every time you exit the game you have to redo it all over again, error phase included.

Is there a reason there's not a persistent path to the lexicon like Polly and other service providers?

**Comment by karashiiro** [comment]
Oh, I was wondering why nobody had reported this — someone did, and I just never saw it 😔

Fixed as of a couple weeks ago: https://github.com/karashiiro/TextToTalk/commit/44053fdba7c103f3b952a6c06e704cbbee46b6de
