### ISSUE TITLE
WebSocket Server only listening on localhost?

### ISSUE THREAD

**Issue by scottmartin** [karashiiro/TextToTalk#189]
Am I wrong or is your websocket server only listening for localhost? I'm playing around with my own TTS server on a Mac on the same network, but I can't seem to get it to connect to the PC's IP address. If so, is there any way you can change it so it will listen for any connection on the network instead of just localhost?

**Comment by karashiiro** [comment]
Missed this — yes, it's hardcoded to `localhost`, I think there was some weird edge case with using `0.0.0.0` I wanted to avoid, but I don't remember now 😶

I'll add an option for this, it's something that should be configurable either way.

**Comment by scottmartin** [comment]
Thank you very much for this and your work on this plugin. Being vision impaired, TextToTalk is almost exclusively the reason I can even play FFXIV at all.
