### ISSUE TITLE
Support for Additional Voices

### ISSUE THREAD

**Issue by Kitsune86** [karashiiro/TextToTalk#2]
Version: 1909 Windows 10

I'm wondering if this plugin pulls from the available voices in control panel on Windows 10 or is limited to Zira / David when using Canadian English (EN) as the default language. In my control panel I have a couple extra voices available that were installed from a third party but they don't show up in the addon

**Comment by karashiiro** [comment]
It can't use all of them, but it's not limited to those -- I have Haruka from my Japanese voice packs in addition to the English voices. Any 64-bit voice package _should_ work if it's installed correctly. 32-bit voice packages cannot work since 64-bit applications (like Dalamud) can't load them.

As a general rule any of the "Desktop" voices in the packages you can install from the Settings app seem to work.

**Comment by lee89tw14** [comment]
So author can't also use the Ayumi's voice right? cause I noticed that Hruka sometimes miss the kannji's pronunciation, not big deal but not sure is that SAPI's problem or what and also not sure will it be fine if changed to another Jp voice.

**Comment by karashiiro** [comment]
If it's not in the list, then it can't be used, no. You can try finding some third-party 64-bit voice packs to see if any of those work, though. Let me know if you find any so I can link to them.

**Comment by QHayward** [comment]
I've managed to get TextToTalk to work with the other Microsoft voices (i.e. Mark, Haruka, etc.)

The process is slightly involved, but these are the instructions I followed:
https://www.ghacks.net/2018/08/11/unlock-all-windows-10-tts-voices-system-wide-to-get-more-of-them/

(alternative instructions: https://www.reddit.com/r/Windows10/comments/96dx8z/how_unlock_all_windows_10_hidden_tts_voices_for/)
(someone's explanation of the issue: https://developercommunity.visualstudio.com/t/support-for-sapi-54-onecore/948724)

**Comment by karashiiro** [comment]
I'll try to add a function that does this automatically.

**Comment by karashiiro** [comment]
Added the VoiceUnlocker project to the solution, which performs this automatically. I'll release a new plugin version soon that has a thing to run this in the config, too.

**Comment by karashiiro** [comment]
Releasing with https://github.com/goatcorp/DalamudPlugins/pull/905
