### ISSUE TITLE
Amazon Polly Voices no longer work with current release

### ISSUE THREAD

**Issue by Ahegaoa** [karashiiro/TextToTalk#20]
They used to work, but after this update they no longer work.

**Comment by karashiiro** [comment]
How are you using Amazon Polly? It looks like a web API.

**Comment by Ahegaoa** [comment]
I installed the Amazon Polly for Windows Plugin. https://i.imgur.com/KSB6Ois.png
https://docs.aws.amazon.com/polly/latest/dg/install-voice-plugin2.html

**Comment by Ahegaoa** [comment]
It is working now after updating to v1.4.4.0 Thank you so much.

**Comment by Ahegaoa** [comment]
They're not working again as of the latest patch 1.4.5

**Comment by karashiiro** [comment]
Tested and working on 1.5, try it again after https://github.com/goatcorp/DalamudPlugins/pull/928 is merged, maybe? I haven't been changing anything that would affect this though, so you might also want to check your installation separately from the plugin.

**Comment by karashiiro** [comment]
Testing this more, it seems to work at first, and then it starts to drop later, so maybe there's a rate limit involved.

**Comment by karashiiro** [comment]
Wait, disregard that, this is unrelated.

**Comment by Ahegaoa** [comment]
I noticed the following, maybe it helps. It is always working for tells outgoing and incoming, party chat, but as for NPC dialogue this is where problems arise. For me, it always reads the NPC dialogue between quotes "[DIALOGUE HERE]" and not any other NPC dialogue. If you remember, I had an issue before where any dialogue with special characters such as < or > or " caused an XML speech error. Now this problem is resolved but the TTS just doesn't work unless I reload the game 3 or 4 times, sometimes more, and it works normally after that until it drops later after a disconnect, or disabling it during voiced cutscenes and reenabling it causes it (using the hotkey ctrl + n) to drop as you stated.

**Comment by karashiiro** [comment]
![image](https://user-images.githubusercontent.com/49822414/124360552-61353900-dbdf-11eb-8f04-24e26a8f14fb.png)

I can't link this to a specific line of code, but I got this a *lot* while trying to replicate this issue. The only thing with this is that this synthesizer doesn't take voice IDs, it does lookups based on the voice name. Anything to do with voice IDs should be handled by the Windows plugin.

**Comment by karashiiro** [comment]
Built-in Polly support is going to be in 1.6.0.2, so you could try that as well, once the testing PR is merged.

**Comment by Ahegaoa** [comment]
Today, I have been using testing version 1.6.0.0 all day, no problems or issues of any kind, no drops, text with special characters worked, both gender voices working with no problems, just one in which I disconnected, relogged, pressed ctrl + n to disable TTS and game crashed. Otherwise, no issues in this version.
