### ISSUE TITLE
Add support for more NPC fields

### ISSUE THREAD

**Issue by Cidan** [karashiiro/TextToTalk#200]
Hi there,

Thank you so much for the plugin! I'm using the websocket server and doing some custom processing, and it would be really great to get some more NPC data in each message, such as most things in [CustomizeIndex](https://dalamud.dev/api/Dalamud.Game.ClientState.Objects.Enums/Enums/CustomizeIndex/). The reasoning here is we can make some more intelligent decisions off of this data and generate more accurate voices.

For example, a short Hyur might be considered a child and have a voice generated as such. A Lalafell on the other hand can have different scaling, etc.

I took a look at the code, and it doesn't seem like it's tooooo hard to add, though a lot of the calls that lead up to the websocket implementation are heavily parameterized, which doesn't make it as easy as just adding this data to a class of some sort.

Any hopes of this extra information being supplied?

**Comment by karashiiro** [comment]
Refactored the code, how easy would it be to add now?

It's not quite one class unfortunately, it's adding a field to `SayRequest`, and then adding a corresponding field to `IpcMessage' for serialization. `IpcMessageMapper` handles converting between them mostly automatically, but might need a bit of customization if the serialization-safe version is too different from what `SayRequest` has.

**Comment by Cidan** [comment]
You read my mind -- I was just looking at exactly what this refactor did. I'll take a stab it it -- looks like I'll start by adding it to `Say` in TextToTalk.cs, fed into `BackendSay`. Let me see what I come up with.
