### ISSUE TITLE
User defined profiles with each their own hotkey?

### ISSUE THREAD

**Issue by ryankhart** [karashiiro/TextToTalk#21]
Normally, I'd prefer to hear TTS for unvoiced NPC dialogue and maybe status effect changes on myself, but sometimes, when I'm just hanging out in a city chatting occasionally, I'd like to hear TTS from a number of additional sources. I'm not always paying close attention to the chatbox.

I think it would be great as a user, to be able to create separate profiles with different TTS settings, each having its own hotkey to switch to it.

As it is now, the hotkey is just a simple toggle, so if each profile's hotkey also worked as a toggle, it would probably need to disable any other previously active profile.

I do already enjoy FFXIV a lot more with this plugin as is. Thank you for creating it!

**Comment by karashiiro** [comment]
Ah, forgot to comment on this; implemented in 1.5, which has been released - closing.
