### ISSUE TITLE
Disable "Character Name says:" completely

### ISSUE THREAD

**Issue by QHayward** [karashiiro/TextToTalk#23]
Perhaps this is a rare use case, but I would really appreciate if there was an option to remove "Character Name says:" completely, even for the first time a character speaks.

**Comment by karashiiro** [comment]
Added to https://github.com/goatcorp/DalamudPlugins/pull/924, will close this if it works well.

**Comment by QHayward** [comment]
Wow, seems to be working great for me.
Thank you, request was fulfilled in two hours, you're amazing.
