### ISSUE TITLE
[BUG] Skip reading voice-acted NPC dialogue no longer works

### ISSUE THREAD

**Issue by EuanFH** [karashiiro/TextToTalk#232]
Since the 7.1 update to dalamund skip reading voice acted NPC dialogue setting is broken and it will play the synthesized and normal voice acted dialog at the same time.

**Comment by Nick026** [comment]
I'm having the same issue unfortunately. You could use /toggletts as a temp fix

**Comment by EuanFH** [comment]
Was wondering if there was a way to temporarily disable it thank you very much.

**Comment by AvarickVRC** [comment]
Hope this gets fixed soon :c

**Comment by karashiiro** [comment]
Sorry for the delay, power/internet were badly affected by the bomb cyclone a couple days ago (no other damage). My internet is still out with no ETA on repairs yet, and I need to conserve my metered mobile hotspot for work right now — will fix if I have leftover data tonight, or if our internet gets repaired soon.

**Comment by karashiiro** [comment]
Should be fixed once the above PR is merged.
