### ISSUE TITLE
Amazon Polly's Neural Engine voice options not listed...at first

### ISSUE THREAD

**Issue by ryankhart** [karashiiro/TextToTalk#27]
Amazon Polly's Neural Engine voice options are not listed, and when I tried "standard" engine and picked voices, and then later switched back to the "neural" engine, the default neural engine voice that had worked before no longer works, and I'm still stuck with whichever "standard" engine voices that I had picked.

**Comment by ryankhart** [comment]
Actually, upon closer inspection, the standard voices are mixed in with the neural voices, but the voice list doesn't show up until I switch to standard and then back to neural again. For now, I just have to look up on Amazon's website which voices are neural and then seek them out in the list.

**Comment by karashiiro** [comment]
I can't replicate this, can you send some screenshots showing what's happening?

**Comment by ryankhart** [comment]
Ok, in order for me to replicate it, I'd need to find out where my settings were getting stored in the files and delete it and relaunch the game. I no longer can replicate it otherwise.

Also, it's entirely possible that maybe this just happened to me because I updated the Text to Talk plugin without relaunching the game. No clue.

**Comment by ryankhart** [comment]
Ok I finally stopped being lazy and just moved my pluginConfigs/TextToTalk.json out of the folder so that it generates a fresh copy with all defaults, and I too wasn't able to reproduce the bug. It may have just been a weird quirk that maybe only affects updates from older versions with specific settings.

I'm going to close this issue now because both of us can't reproduce the bug, but if anyone else reads this later, just maybe we can open this back up or something.

**Comment by ryankhart** [comment]
Just something I noticed just now @karashiiro. I left FFXIV running and then updated the TextToTalk plugin without first relaunching FFXIV, and it broke NPC dialogue altogether. Then I relaunched FFXIV and that fixed it. I think that might have been the edge case for why I had problems with the Amazon Polly feature initially as well.

**Comment by karashiiro** [comment]
Huh, I might be forgetting to dispose something somewhere when the plugin unloads, I’ll look at that.

**Comment by karashiiro** [comment]
Closing this unless it's still a problem.
