### ISSUE TITLE
Long "—" used in FFXIV dialogue leads to individual pronunciation of characters.

### ISSUE THREAD

**Issue by qusteka** [karashiiro/TextToTalk#29]
As the titles suggests the "—" character also known as emdash (at least i think that's what is used) makes TTS read each character individually rather than read the word infront and after the "—". So something like

behold Great King moogle — first of his name etc. sounds really silly.

would there be any way to make — be interpreted "-" instead? because "-" is treated as a normal dash and doesn't cause words to be read as individual characters.

**Comment by qusteka** [comment]
It seems like that change did not fix it. While "—" looks like an EMDASH in ffxiv to me it's apparently not. The problem still remains :(. Thank you for trying to fix it so quickly though.

**Comment by qusteka** [comment]
https://www.fontspace.com/unicode/analyzer#e=5LiA

could be this, that'd be the japanese character for "1" but it looks pretty much identical to an emdash

**Comment by karashiiro** [comment]
There are multiple characters the game uses for emdashes, the one that I'm currently using isn't actually an emdash either, no clue what it is. I'll add another replace for that and see if that fixes it.

**Comment by qusteka** [comment]
Dang the game has strange text standardization. Thanks though, really appreciate your work.

**Comment by qusteka** [comment]
I noticed you've specifically updated the Dash issue on the polly backend but personally I'm having the same issue on a custom System voice. Sorry for the bother but if possible implementing it on that as well would be great.

**Comment by karashiiro** [comment]
Yeah, I was in a bit of a rush so I didn’t apply that to everything before I could test it extensively - I’ll fix that tonight once I’m at my computer.

**Comment by karashiiro** [comment]
Releasing with https://github.com/goatcorp/DalamudPlugins/pull/962
