### ISSUE TITLE
Awkward pronunciation of some abbreviations with Amazon Polly

### ISSUE THREAD

**Issue by ryankhart** [karashiiro/TextToTalk#31]
I'm using the Amazon Polly voices, which are great, but sometimes it extrapolates abbreviations like "nin" to mean "Nine Inch Nails" 
 or "res" to mean "residential" and it always throughs me for a loop every time I hear it. It would be pretty sweet to be able to disable that and/or be able to set our own custom pronunciations for words.

I don't know how the backend of this is set up, but assuming it's an Amazon Polly issue, then this issue isn't really a bug with this plugin but more of a feature request to be able to better utilize Amazon Polly.

I'll still love and use this plugin regardless.

**Comment by karashiiro** [comment]
Already on it, see https://github.com/karashiiro/TextToTalk/commit/569743bec186dd2a8d3bcecab76addc87e1ae9f2 onwards. Once I test it a bit more I'll merge a new release.

**Comment by karashiiro** [comment]
Merging with https://github.com/goatcorp/DalamudPlugins/pull/964

**Comment by karashiiro** [comment]
Merged into testing — closing.

**Comment by Ahegaoa** [comment]
hi @ryankhart i wrote a lexicon file that solves your issue and would like to post it here as figuring out how to write aliases and pronunciations took me some research. I hope this helps solves your problem and sets you on the right path. You may also refer to [SAMPA chart](https://en.wikipedia.org/wiki/SAMPA_chart_for_English) here for pronunciation.

```
<?xml version="1.0" encoding="UTF-8"?>
<lexicon version="1.0" 
      xmlns="http://www.w3.org/2005/01/pronunciation-lexicon"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:schemaLocation="http://www.w3.org/2005/01/pronunciation-lexicon 
        http://www.w3.org/TR/2007/CR-pronunciation-lexicon-20071212/pls.xsd"
      alphabet="ipa" 
      xml:lang="en-US">
  <lexeme>
    <grapheme>nin</grapheme>
    <alias>ninja</alias>
  </lexeme>
  <lexeme>
    <grapheme>res</grapheme>
    <phoneme>rEz</phoneme>
  </lexeme>
</lexicon>
```
