### ISSUE TITLE
Read current text when Enabling TTS while dialogue box is open, don't read current text when enabling TTS while dialogue box is closed.

### ISSUE THREAD

**Issue by johnysandels** [karashiiro/TextToTalk#32]
In the XLDev Addon Inspector it is possible to see if the dialogue box is visible or not, so it should be possible to detect if the dialogue box is open.
I think that if the dialogue window **is open**, enabling TTS through the keybind shortcut or through chat commands, it should start reading the currently open dialogue box.
If the dialogue window is **not open** when enabling the TTS through the keybind or chat command, it should **not** read the current dialogue.

I hope that all makes sense! feel free to reach out for clarification if I said it weird!
Still really enjoying this plugin! it's been great for the Hildebrand missions!

**Comment by karashiiro** [comment]
Looks like https://github.com/karashiiro/TextToTalk/commit/2b1516501fd3500e1f2e951b32d211f0f0881979 fixes this, even if it wasn't intentional - closing.
