### ISSUE TITLE
'TTS disabled' message seems to be broken

### ISSUE THREAD

**Issue by QHayward** [karashiiro/TextToTalk#38]
I'm not entirely certain if it's just for me, but the 'TTS disabled' echo message seems to not be working right now.

**Comment by karashiiro** [comment]
On testing or on the main version? Will look into it.

**Comment by QHayward** [comment]
I'm on the testing version

**Comment by QHayward** [comment]
I can confirm I only have the problem on the testing version

**Comment by karashiiro** [comment]
I have an [open PR](https://github.com/goatcorp/DalamudPlugins/pull/971) that should fix it, just waiting on that to be merged.
