### ISSUE TITLE
Nested Replacements (w priority system) for lexicon

### ISSUE THREAD

**Issue by johnysandels** [karashiiro/TextToTalk#46]
Would allow for priority for replacements, allowing the name Y'stola to have priority over `'s`

Tbh this isn't that important since the main usage of the lexicons being used is names, not recreating a whole language, so the only reason this would be helpful is for `'s`'s after a name

**Comment by karashiiro** [comment]
This is technically done - my main focus is now on fixing the broken parts, which we're covering in #48. Closing.
