### ISSUE TITLE
More German Voices for Amazon Polly

### ISSUE THREAD

**Issue by Waitsnake** [karashiiro/TextToTalk#47]
At the moment the only German Voice in the option list for Amazon Polly is "Vicki".

According to [this site](https://docs.aws.amazon.com/polly/latest/dg/voicelist.html) there are two more German voices "Hans" and "Marlene". Could you please enable those in the option list as well?

I took a looked into the AWSSDK.Polly.dll binary that you use and the strings "Hans" and "Marlene" can be found inside and so I hope it is just a change in how the TTS plugin uses the Amazon Polly API.

**Comment by karashiiro** [comment]
Have you checked both engines? Not every voice is enabled in every engine, and I don't have any control over what is and isn't enabled in each.

**Comment by Waitsnake** [comment]
Sorry, my fault. I was not aware of the different availability of the voices in the two different engines.
"Neutral" engine only allows "Vicki" while "Standard" engine allows "Vicki", "Hans" and "Marlene".
