### ISSUE TITLE
Add a print to chat when switching presets that describes which preset it just switched to.

### ISSUE THREAD

**Issue by ryankhart** [karashiiro/TextToTalk#55]
I came up with this idea because I had taken a small break from the game and when I came back, I had forgotten what my keyboard shortcuts were to switch to which preset, so I either had to try the various keyboard shortcuts I had made and wait to find out if I switched to the right preset, or look it back up in the plugin settings.

I know that it already echoes in chat when I enable or disable the plugin, but currently, no echo for switching presets. Hopefully, it's a relatively simple feature to add in the future.

**Comment by ryankhart** [comment]
With my newfound experience with this codebase. I managed to figure out how to implement this one myself. I just have to wait until we get plugin support back for patch 6.1 to test out my changes.

**Comment by karashiiro** [comment]
Released v1.14
