### ISSUE TITLE
specific proneme symbol not working

### ISSUE THREAD

**Issue by johnysandels** [karashiiro/TextToTalk#58]
the proneme symbol ʤ causes the sentence not read out if it incudes the word with that symbol in the lexicon. The ʤ symbol is responsible for the hard J sound in jazz or jump

**Comment by karashiiro** [comment]
Is this in the System backend or Polly?

**Comment by karashiiro** [comment]
Have you tried using d͡ʒ? The system's SSML engine might use some alternative rendition of that. There's a bunch at the top of this article: https://en.wikipedia.org/wiki/Voiced_postalveolar_affricate

**Comment by johnysandels** [comment]
Yes that symbol seems to work! I also noticed that the ʤ symbol actually does work with the british voice of Havel, but doesn't work for the US Voice David and Zira. the d͡ʒ symbol works for both British and American region voices though.

**Comment by johnysandels** [comment]
I would suggest implementing a replacer of ʤ to d͡ʒ since it seems to work just fine. but this work around works as is, and it's fine if you don't wanna do it xD
closing this either way!

**Comment by karashiiro** [comment]
I didn't communicate this, but that's why I left this issue open 🥴 I'm leaving it open until I add a replacement for it.

**Comment by johnysandels** [comment]
sounds good! sorry about that!

**Comment by karashiiro** [comment]
Fixed in v1.13.1
