### ISSUE TITLE
Option to disable during voiced cutscenes

### ISSUE THREAD

**Issue by karashiiro** [karashiiro/TextToTalk#7]
See title. For this to happen we need some list of voiced cutscenes and a method of detection.

**Comment by johnysandels** [comment]
I was using Anna's Sound Log And it seems like all voice lines come from `cut/{ex{1-3]/sound/voicem/..`(ex number varies by expansion the voice is coming from) and they fire right as the text box comes up. So you could scan for those voice files firing while the current condition is `Current ID: 35 Enum: OccupiedInCutSceneEvent` and not trigger TTS if a sound from that directory fires when the dialogue box pops up.

**Comment by karashiiro** [comment]
Oh, this could work. I might be able to pull file load detection from Penumbra or something.

**Comment by johnysandels** [comment]
Well I checked how the files load with reslogger, and it loads al the voices at the beginning of the cutscene during the loading screen and fire at the appropriate time. Wonder if Anna's Sound Logger would be a good place to start.

**Comment by karashiiro** [comment]
Oh, I just woke up 🥴 Will check that.

**Comment by karashiiro** [comment]
Actually, where is that? Not seeing it on her plugin repo.

**Comment by johnysandels** [comment]
It's part of her Sound Filter plugin

**Comment by johnysandels** [comment]
Oh not sure if you know this, but I remember reading something about sound file streaming, and how Anna's sound logger disables it so it can see when certain sounds are playing. I think they said Penumbra does the same thing. So I was able to see the sound paths for cutscene text that way.
Hope that's helpful!

**Comment by johnysandels** [comment]
> Oh, this could work. I might be able to pull file load detection from Penumbra or something.

I think Penumbra does disable sound streaming so this could work too.

With sound streaming disabled it loads the voice audio file right as the NPC talks.

**Comment by dedren** [comment]
Oh this would be awesome for us controller players who stream to TV and are far from their keyboards 😀!
