### ISSUE TITLE
npc tts volume isnt affected by the volume settings

### ISSUE THREAD

**Issue by masterkiller332** [karashiiro/TextToTalk#80]
when i turn the volume down in the plugin settings the npcs still sound like its on the loudest settings

**Comment by karashiiro** [comment]
Can you provide the following information?

- Backend (System/Polly)
- Voice name
- Your dalamud.log file (`%AppData%/XIVLauncher/dalamud.log`)

**Comment by masterkiller332** [comment]
im useing system the voice is minecrosoft david desktop (it changes depending on the gender of the character)

**Comment by masterkiller332** [comment]
[dalamud.log](https://github.com/karashiiro/TextToTalk/files/8092335/dalamud.log)

**Comment by masterkiller332** [comment]
i am an idot and didnt figure out that i need to change the volume for each voice indvidualy
