### ISSUE TITLE
Is there a way to prevent it from speaking the things you say?

### ISSUE THREAD

**Issue by karashiiro** [karashiiro/TextToTalk#95]
### Discussed in https://github.com/karashiiro/TextToTalk/discussions/94

<div type='discussions-op-text'>

<sup>Originally posted by **OmsagroSylph** April 15, 2022</sup>
I would like to prevent it from reading out things typed by me.  I tried to use an exclusion which didn't seem to work, but maybe I didn't format things correctly.</div>

**Comment by ryankhart** [comment]
I like this idea to not read text typed by the player. It might even make for a good default to exclude player chat.

**Comment by karashiiro** [comment]
This can be implemented by checking the sender SeString in the chat message handler, and seeing if the name equals the current player's name. Even better is if the SeString has a payload with an ID or something that uniquely identifies the current play from anything else with the same name, but I don't know what's in there off the top of my head.

**Comment by karashiiro** [comment]
Implemented in v1.19
