### ISSUE TITLE
Empty voice list in AWS backend after update

### ISSUE THREAD

**Issue by karashiiro** [karashiiro/TextToTalk#97]
![](https://i.imgur.com/coHyJMz.png)

**Comment by johnysandels** [comment]
I also found that trying to login to amazon polly crashes the game

**Comment by ryankhart** [comment]
> I also found that trying to login to amazon polly crashes the game. logging in seems to work the second time, after relaunching and voices show up again.

I made a issue already for a bug that sounds like the one you experienced here: https://github.com/karashiiro/TextToTalk/issues/98

**Comment by karashiiro** [comment]
Possibly fixed in v1.13.1

**Comment by ryankhart** [comment]
The empty list bug was fixed for me after I pulled from the main branch in that past 30 minutes.

**Comment by ryankhart** [comment]
I'm going to close this issue down, if you don't mind. I also tested once more by deleting my local build and downloading 1.13.1 from the official Dalamud repo. Seems fixed to me, but we can reopen it later if there are still problems for some people.
