### ISSUE TITLE
NullReferenceException causes game crash to desktop if user logs into Amazon Polly while TTS is in progress

### ISSUE THREAD

**Issue by ryankhart** [karashiiro/TextToTalk#98]
I got a a NullReferenceException crash to desktop twice in a row when I was listening to an NPC speak. I realized that it wasn't the Amazon Polly voices that I expected, so while listening, I opened up the TTT config, went to Synthesizer tab->Voices, and I clicked "Save and Login". That crashed with this message in the screenshot on both times.

![image](https://user-images.githubusercontent.com/3673962/163657908-c1b81ee6-1827-4fb2-854d-b9cf72068935.png)

I was able to reproduce this same crash in one other way as well by switching from Amazon Polly while logged to the System "Voice backend" while the TTS was in progress.

I tried it again several times by switching the following while a TTS was in progress:
- Switching from standard "Voice backend" to Amazon Polly "Voice backend"
- Switching from standard voice to a different standard voice.
- Switching from Amazon Polly voice to a different Amazon Polly voice

None of these last 3 test cases could reproduce the crash.

**Comment by karashiiro** [comment]
Possibly fixed in v1.13.1

**Comment by ryankhart** [comment]
It's fixed for me. I can't get the game to crash again following my repro steps specified above. I'll close this issue for now. If it crops back up, I'll reopen it later.
